#!/bin/sh


echo "Patch sysupgrade configuration folder (only /etc/config) "

echo "/etc/config" > /etc/sysupgrade.conf

# sysupgrade: exclusively consider files in /etc/sysupgrade.conf and no other config files
patch -l /sbin/sysupgrade << 'EOF'
@@ -20,6 +20,7 @@
 CONF_BACKUP_LIST=0
 CONF_BACKUP=
 CONF_RESTORE=
+CONF_EXCLUSIVE=1
 NEED_IMAGE=
 HELP=0
 TEST=0
@@ -50,6 +51,7 @@
                -r|--restore-backup) CONF_RESTORE="$2" NEED_IMAGE=1; shift;;
                -l|--list-backup) CONF_BACKUP_LIST=1;;
                -f) CONF_IMAGE="$2"; shift;;
+               -e) CONF_EXCLUSIVE=0;;
                -F|--force) export FORCE=1;;
                -T|--test) TEST=1;;
                -h|--help) HELP=1; break;;
@@ -221,12 +223,30 @@
        return 0
 }

+build_list_of_exclusive_config_files() {
+    local file="$1"
+
+    local paths
+    paths=$(sed -ne '/^[[:space:]]*$/d; /^#/d; p' /etc/sysupgrade.conf 2>/dev/null)
+
+    if [ -z "$paths" ]; then
+       touch "$file"
+        return 0
+    fi
+
+    find $paths \( -type f -o -type l \) $find_filter 2>/dev/null | sort -u > "$file"
+
+    return 0
+}
+
 if [ $SAVE_OVERLAY = 1 ]; then
        [ ! -d /overlay/upper/etc ] && {
                echo "Cannot find '/overlay/upper/etc', required for '-c' or '-o'" >&2
                exit 1
        }
        sysupgrade_init_conffiles="build_list_of_backup_overlay_files"
+elif [ "$CONF_EXCLUSIVE" = 1 ]; then
+    sysupgrade_init_conffiles="build_list_of_exclusive_config_files"
 else
        sysupgrade_init_conffiles="build_list_of_backup_config_files"
 fi
EOF


