---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/11/24 4:58 PM
---

package.path = "/etc/tf_clish/scripts/poe/?.lua;" .. package.path

local tf = require "tf_module"

local snmp_status_poe = {}

local poe_statusEnum = {
    ["Searching"] = 2,
    ["Delivering power"] = 1
}

local function snmp_getPoeStatus(mibObj, portNum)
    local poeInfoJson = tf.collectJsonTable("ubus call poe info")
    local res = ""
    local status = "OK"
    local count = 8
    if tonumber(portNum) > count then
        status = "over_index"
        return nil, status
    elseif tonumber(portNum) < 1 then
        status = "zero_index"
        return nil, status
    end

    local poePorts = poeInfoJson["ports"]
    poePorts = poePorts["lan" .. portNum]

    --print("mibObj.name = " .. mibObj.name .. " portNum = " .. portNum)
    if (mibObj.name == "portPoeStatusState") then
        local poePortStatus = poePorts["status"]
        res = poe_statusEnum[poePortStatus]
    elseif (mibObj.name == "portPoeStatusPower") then
        if poeInfoJson["power"] ~= nil then
            res = poeInfoJson["power"]
        else
            res = "0"
        end
    elseif (mibObj.name == "portPoeStatusIndex") then
        res = portNum
    end
    return res, status
end

snmp_status_poe.main =
{
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getPoeStatus,
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeStatusIndex",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.5.1.1.2"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            up = "1",
            down = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = snmp_getPoeStatus,
        name = "portPoeStatusState",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.5.1.1.3"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.3"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getPoeStatus,
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeStatusPower",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.6.1.1.1.1"
    },
}

return snmp_status_poe

