---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/11/24 4:58 PM
---

local tf = require "tf_module"
local snmp_status_sfp = {}

local function snmp_getSPFdata(snmp_obj, index)
    local jsonInfo
    local res = ""
    local name = ""
    local status = "OK"

    if tonumber(index) <= 2 then
        if snmp_obj.name == "portSfpIndex" then
            res = index
            --elseif snmp_obj.name == "portSfpTxOutPowerDb" or snmp_obj.name == "portSfpRxOutPowerDb" then
            --    res = "3227"
        else
            name = snmp_obj.name .. "_" .. tostring(index)
            jsonInfo = tf.getUbusDataByName(name)
            res = jsonInfo[name]
        end

        if (snmp_obj.isZero == "yes") then
            res = tonumber(res) + 1
        end
    elseif tonumber(index) > 2 then
        status = "over_index"
    end
    return res, status
end

snmp_status_sfp.main =
{
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpIndex",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.2"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.2"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpPresent",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.3"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.3"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpSignalDetect",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.4"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.4"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "STRING",
        ubusType = snmp_getSPFdata,
        name = "portSfpVendor",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.5"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.5"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "STRING",
        ubusType = snmp_getSPFdata,
        name = "portSfpOui",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.6"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.6"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "STRING",
        ubusType = snmp_getSPFdata,
        name = "portSfpPartNumber",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.7"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.7"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "STRING",
        ubusType = snmp_getSPFdata,
        name = "portSfpRevision",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.8"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.8"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTemperature",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.9"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.9"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpVoltage",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.10"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.10"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpBiasCurrent",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.11"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.11"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTxOutPower",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.12"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.12"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTxOutPowerDb",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.13"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.13"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpRxOutPower",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.7.1.1.14"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.14"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getSPFdata,
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpRxOutPowerDb",
        next_oid = "1.3.6.1.4.1.42019.3.2.2.8.1"
    },
}

return snmp_status_sfp

