---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/11/24 4:58 PM
---
local tf = require "tf_module"

local snmp_config_poe = {}

local function snmp_getPoeState(mibObj, portNum)
    local res      = ""
    local status   = "OK"

    local count = 8
    if tonumber(portNum) > count then
        status = "over_index"
        return nil, status
    elseif tonumber(portNum) < 1 then
        status = "zero_index"
        return nil, status
    end

    if mibObj.name == "portPoeIndex" then
        res = portNum
    elseif mibObj.name == "portPoeState" then
        res = tf.executeCommand("uci get port.lan" .. portNum .. ".poe")
    end

    if mibObj.isEnum == "yes" then
        res = res .. "d"
        res = mibObj.enum[res]
    end
    return res, status
end

snmp_config_poe.main =
{
    ["1.3.6.1.4.1.42019.3.2.1.3.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = snmp_getPoeState,
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeIndex",
        next_oid = "1.3.6.1.4.1.42019.3.2.1.3.1.1.2"
    },
    ["1.3.6.1.4.1.42019.3.2.1.3.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            enabled = "1",
            disabled = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = snmp_getPoeState,
        name = "portPoeState",
        isZero = "no",
        next_oid = "1.3.6.1.4.1.42019.3.2.1.4.1",
    },
}

return snmp_config_poe

