#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/26/24 2:25 PM
---

--print("---------------- get model ver 1.3 ----------")

local tf = require "tf_module"

local system_board =
{
    kernel     = "kernel",
    hostname   = "hostname",
    system     = "system",
    model      = "model",
    board_name = "board_name",
    rootfs_type = "rootfs_type",
    release     = "release"
}

local release_t  = {
    distribution = "distribution",
    version = "version",
    revision = "revision",
    target = "target",
    description = "description"
}

local modelTable =
{
    ["PSW+UPS-Box 8x2Pro"] = 32,
    ["PSW+Box 8x2Pro"]     = 33,
    ["PSW+UPS-Ex 8x2Pro"]  = 34,
    ["PSW+Ex 8x2Pro"]      = 35,
};

local function getModelType(input_string)
    local index = 0
    if modelTable[input_string] ~= nil and modelTable[input_string] ~= "" then
        index = modelTable[input_string]
    end
    print(7)
end

local function getFwVersion(version)
    for part in version:gmatch("[^.]+") do
        print(part)
    end
end

local function main_getModel()
    local jsonData = tf.collectJsonTable("ubus call system board")
    if jsonData ~= nil then
        getModelType(jsonData[system_board.model])
        getFwVersion(jsonData[system_board.release].version)
    end
end

main_getModel()


