#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 3/1/24 10:51 AM
---

local tf = require "tf_module"

local timeInfo = {
    localtime   = "localtime",
    uptime      = "uptime"
}

local function main_getTimeInfo()
    local  cmd_getTimeInfo = "ubus call system info"
    --print(cmd_getDeviceInfo)
    local jsonData = tf.collectJsonTable(cmd_getTimeInfo)
    if type(jsonData) == "table" then
        local uptime = ""
        if jsonData[timeInfo.uptime] ~= nil then
            uptime = jsonData[timeInfo.uptime]
        end
        print(uptime)
    else
        print("")
    end
end

main_getTimeInfo()