#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/28/25 10:01 AM
---

local function get_processStatus()
    local tf = require "tf_module"
    local cmd = "ubus -S call luci getProcessList"

    local res_json = tf.collectJsonTable(cmd)
    if res_json == nil or res_json["result"] == nil then
        print "proc_not_valid"
        return
    end

    res_json = res_json["result"]

    if type(res_json) == "table" then
        if arg[1] == nil then
            --print("no_procName")
            for i, s in pairs(res_json) do
                if s["COMMAND"] ~= nil then
                    print(i .. " - " .. s["COMMAND"])
                end
            end
            return
        end
        local print_pid = ""
        if arg[2] ~= nil then
            print_pid = arg[2]
        end

        local program_name = arg[1]
        for _, s in pairs(res_json) do
            if s["COMMAND"] == program_name then
                if print_pid == "pid" then
                    print("PID = " .. s["PID"])
                end
                print "running"
                return
            end
        end
        print "not_running"
    end
end

get_processStatus()




