
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/11/25 12:25 PM
---


local print_module = {}

print_module.critical =
{
    regular             = "critical: ",
    arg_wrong           = "critical: argument is wrong",
    delete_ifconfig     = "critical: wrong command to delete ifconfig",
    set_ifconfig        = "critical: wrong command to set ifconfig",
    config_is_wrong     = "critical: config is wrong",
    config_bridge_vlan  = "critical: config bridge-vlan",
    if_list             = "critical: interface list is empty",
    board               = "critical: board info is empty",
    system              = "critical: system info is empty",
    time                = "critical: time info is empty",
}

print_module.info =
{
    successfull = "info: network configuration successfully",
    if_config   = "info: for configure interface, yuo need to run command: *network ipif config* with the necessary arguments"
}

print_module.warning = {
    vlan_not_found = "warning: vlan not found - ",
    ifname_used    = "warning: interface is used - ",
    ifname_deleted = "warning: interface marked as DELETED",
    vlan_delete_1   = "\nwarning:\n \t\tThis operation may result in LOSS OF COMMUNICATION with the switch",
    vlan_delete_2   = "\t\tBefore saving the changes, make sure they are correct !!!",
    vlan_delete_3   = "\nwarning:\n \t\tVLAN is Management VLAN and can not be deleted !!!",
}

print_module.error =
{
    dev_nil         = "error: device not found",
    if_name_long    = "error: interface name is very long",
    vlan_id         = "error: vlan id not corrected"
}



return print_module
