#!/bin/sh /etc/rc.common
START=95
STOP=01
USE_PROCD=1

CONFIG_FILE="/var/etc/hostapd.conf"
CTRL_INTERFACE="/var/run/hostapd"
PORT_MNGT_SCRIPT="/usr/libexec/network/8021x.sh"

get_logging_config(){
	local logger_syslog_level
	config_get logger_syslog_level $1 logger_syslog_level
	[ -n "$logger_syslog_level" ] && echo -e "logger_syslog_level=$logger_syslog_level" >> ${CONFIG_FILE}
}

make_config(){
	local enable
	config_get_bool enable $1 enable
	if [ $enable == '1' ]; then
		local auth_server_addr
		local auth_server_port
		local auth_server_shared_secret
		local acct_server_addr
		local acct_server_port
		local acct_server_shared_secret
		local eap_reauth_period
		local ca_cert
		local server_cert
		local private_key

		config_get auth_server_addr $1 auth_server_addr
		config_get auth_server_port $1 auth_server_port
		config_get auth_server_shared_secret $1 auth_server_shared_secret

		config_get acct_server_addr $1 acct_server_addr
		config_get acct_server_port $1 acct_server_port
		config_get acct_server_shared_secret $1 acct_server_shared_secret

		config_get eap_reauth_period $1 eap_reauth_period

		config_get ca_cert $1 ca_cert
		config_get server_cert $1 server_cert
		config_get private_key $1 private_key


		mkdir -p "$(dirname ${CONFIG_FILE})"
		> ${CONFIG_FILE}
		echo -e "driver=wired" >> ${CONFIG_FILE}
		echo -e "logger_syslog=-1" >> ${CONFIG_FILE}

		config_load 8021x
		config_foreach get_logging_config logs

		echo -e "logger_stdout=-1" >> ${CONFIG_FILE}
		echo -e "logger_stdout_level=0" >> ${CONFIG_FILE}
		echo -e "ctrl_interface=$CTRL_INTERFACE" >> ${CONFIG_FILE}
		echo -e "ctrl_interface_group=0" >> ${CONFIG_FILE}

		[ -n "$auth_server_addr" ] && echo -e "auth_server_addr=$auth_server_addr" >> ${CONFIG_FILE}
		[ -n "$auth_server_port" ] && echo -e "auth_server_port=$auth_server_port" >> ${CONFIG_FILE}
		[ -n "$auth_server_shared_secret" ] && echo -e "auth_server_shared_secret=$auth_server_shared_secret" >> ${CONFIG_FILE}

	    [ -n "$acct_server_addr" ] && echo -e "acct_server_addr=$acct_server_addr" >> ${CONFIG_FILE}
		[ -n "$acct_server_port" ] && echo -e "acct_server_port=$acct_server_port" >> ${CONFIG_FILE}
		[ -n "$acct_server_shared_secret" ] && echo -e "acct_server_shared_secret=$acct_server_shared_secret" >> ${CONFIG_FILE}

		echo -e "ieee8021x=1" >> ${CONFIG_FILE}
		echo -e "use_pae_group_addr=1" >> ${CONFIG_FILE}
		echo -e "eapol_version=2" >> ${CONFIG_FILE}

		[ -n "$eap_reauth_period" ] && echo -e "eap_reauth_period=$eap_reauth_period" >> ${CONFIG_FILE}
		[ -n "$ca_cert" ] && echo -e "ca_cert=$ca_cert" >> ${CONFIG_FILE}
		[ -n "$server_cert" ] && echo -e "server_cert=$server_cert" >> ${CONFIG_FILE}
		[ -n "$private_key" ] && echo -e "private_key=$private_key" >> ${CONFIG_FILE}
	fi
}


run_8021x()
{
   	local ifname
	local enable
    config_get_bool enable $1 enable
	if [ $enable == '1' ]; then
		config_get ifname $1 ifname
		${PORT_MNGT_SCRIPT} $ifname block_all

		procd_open_instance
		procd_set_param command /usr/sbin/hostapd_cli -B -i $ifname -a ${PORT_MNGT_SCRIPT}
		procd_set_param stderr 1
        procd_set_param stdout 1
		procd_close_instance

		procd_open_instance
		procd_set_param command /usr/sbin/hostapd -i $ifname "${CONFIG_FILE}"
		procd_set_param stderr 1
        procd_set_param stdout 1
		procd_close_instance


		echo "802.1x has started on interface $ifname"
	fi
}

stop_8021x()
{
	local ifname
	local enable
	config_get_bool enable $1 enable
	config_get ifname $1 ifname
	${PORT_MNGT_SCRIPT} $ifname allow_all
	echo "802.1x has stoped on interface $ifname"
}

start_service() {
	config_load 8021x
	config_foreach make_config general
	config_foreach run_8021x interface
}

stop_service() {
	config_load '8021x'
	config_foreach stop_8021x 'interface'
	killall hostapd
}

service_triggers()
{
	procd_add_reload_trigger "8021x"
}


reload_service()
{
  echo "reload_service autorestart"
  stop
  start
}



